[private]
help:
    @just --list

version_file := source_directory() / "target" / ".new_version"

publish version="$(read -p 'New version: ' v; echo $v)":
    grep '^version =' Cargo.toml
    @echo {{version}} > {{version_file}}
    sed -i 's/^version = "[^"]*"$/version = "'"$(cat {{version_file}})"'"/' Cargo.toml
    grep '^version =' Cargo.toml
    cargo test --no-default-features
    cargo test
    git add Cargo.*
    git commit -m "Bump Rust version to $(cat {{version_file}})"
    git tag "rust-v$(cat {{version_file}})" -m "v$(cat {{version_file}})"
    cargo publish
    git push
    git push --tags
